export const dom = {
  motivateBtn: document.getElementById("motivateBtn"),
  motivationText: document.getElementById("motivationText"),
  greetBtn: document.getElementById("greetBtn"),
  nameInput: document.getElementById("nameInput"),
  greetingText: document.getElementById("greetingText"),
  calculateBtn: document.getElementById("calculateBtn"),
  studyHoursInput: document.getElementById("studyHours"),
  studyResult: document.getElementById("studyResult"),
  addSessionBtn: document.getElementById("addSessionBtn"),
  sessionCountDisplay: document.getElementById("sessionCount"),
  totalHoursDisplay: document.getElementById("totalHours"),
  averageHoursDisplay: document.getElementById("averageHours"),
  averageProgressBar: document.getElementById("averageProgressBar"),
  sessionList: document.getElementById("sessionList"),
  taskInput: document.getElementById("taskInput"),
  addTaskBtn: document.getElementById("addTaskBtn"),
  taskList: document.getElementById("taskList"),
  filterButtons: document.querySelectorAll(".filter-buttons button"),
};
